### ISSUE TITLE
parametrised network in ctau

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#2]
investigate using a parametrised network and related performance as a function of **ctau**

- [x] need to save ctau when unpacking nanox samples (currently only displacement in lab frame is available)
- [x] generate fake ctau values for all backgrounds while unpacking
- [x] train network using 1mm and 1m samples and compare performance for single trainings on 10mm and 100mm samples

_Note: This is only a first test to understand training of parametrized networks. Ultimately it would be best to train on displacement (or displacement in transverse plane) instead since ctau is model-dependent_

**Comment by vcepaitis** [comment]
Setup is ready, need to wait for GPU nodes to be fixed
