### ISSUE TITLE
define analysis categories for signal extraction

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#22]
* simplify/study RA1 binning scheme
* test new variables related to displacement (SV, tagger out, etc.)
* optional: setup combine for expected limits

**Comment by matt-komm** [comment]
problem: discriminant depends on ctau -> background distribution changes -> need to define multiple binning schemes (3?)

**Comment by vcepaitis** [comment]
Duplicate with https://app.zenhub.com/workspace/o/llpdnnx/nanox/issues/37 ?
@matt-komm

**Comment by matt-komm** [comment]
yes it's duplicate of my notes during a meeting
