### ISSUE TITLE
implement optional photon veto

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#27]
use cut-based loose id: https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2
(might be available already as a flag in nanoaod)

**Comment by vcepaitis** [comment]
Remember to run over gamma+jets events.
Also add any other interesting variables for network training.

**Comment by vcepaitis** [comment]
@matt-komm Would we still need this if we're not going to use the gamma+jets control region?

**Comment by matt-komm** [comment]
this is not needed atm
