### ISSUE TITLE
Investigate jet id efficiency for heavily displaced jets

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#3]
Current loose jet ID (https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID13TeVRun2016) maybe suboptimal when jets are heavily displaced since e.g. no charged hadrons are reconstructed anymore

**Comment by daiktas** [comment]
@matt-komm Is this the right page?
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016

**Comment by matt-komm** [comment]
yes

**Comment by vcepaitis** [comment]
Can we say this is done? @matt-komm

**Comment by matt-komm** [comment]
yes - so conclusion:
* jet inefficiency only seen for ctau=10m;
* only ISR jet reconstructed for ctau=100m 
=>  "small" increase of jet acceptance at edge of parameter space using "own" jet id will be too much work considering that also jet energy scale needs to be retuned/validated
