### ISSUE TITLE
find optimal binning strategy for limits

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#37]
potential observables for binning/distribution
* HT (sensitive to llp mass)
* MHT
* #jets
* #llp jets
* llp discriminant
* #SVs
* ...
=> idea: put all variables into a BDT and check which variables it uses for the e.g. first 3 trees (see xml file)

**Comment by vcepaitis** [comment]
* Cut on say prob(LLP) > 0.95 might make it easier to devise the binning scheme. 
* Check correlations between variables (from BDT training?)
