### ISSUE TITLE
Fix NAN values

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/NANOX#8]
The following input variables contain sometimes NAN values:
* cpf_trackSip2dSig
* cpf_trackSip3dSig
* sv_normchi2

Note: NAN/INF values are set to 0 in the RootReader so this is fine in the training but should be dealt with in a general way also to prevent odd results during evaluation.

**Comment by vcepaitis** [comment]
It would be nice to investigate how often this occurs and if it would be safe to drop such events. One way of dealing with this would be to replace NaN with some mean value of that distribution.

**Comment by matt-komm** [comment]
It occurs in about 10% of all jets. Most likely this happens when:
* the error in the significance is 0 for cpf_trackSip2dSig & cpf_trackSip3dSig
* ndof is 0 for sv_normchi2

So this can just be set to 0 or some other value during training/evaluation. However NAN should not be stored in the NANOX trees in the first place.
